// 6.19 E: writes docs/SPANISH_REVIEW.md from the L10N table in index.html, English and the Spanish DRAFT side by side,
// for a human translator and the clinician. Run: npm run spanish-review (stage619.test.js fails if the file drifts).
const fs=require('fs'), path=require('path');
const {JSDOM}=require('jsdom');
function build(){
  const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
  const w=new JSDOM(html,{url:'https://zigzagmind.com/',runScripts:'dangerously',pretendToBeVisual:true,beforeParse(w){ w.scrollTo=()=>{}; }}).window;
  const L=w.eval('L10N'), crisis=k=>w.eval(`l10nIsCrisis(${JSON.stringify(k)})`);
  const cell=x=>String(x).replace(/&amp;/g,'&').replace(/\|/g,'\\|');
  const AREA={help:'Help button',tab:'Tab bar',r988:'988 buttons (crisis screens and elsewhere)',person:'Trusted-person buttons',cw:'Code word button',copy:'Copy buttons (computers)',
    home:'Home',ob:'Onboarding',common:'Shared',privacy:'Privacy link',crisis:'Crisis screens',crisisfull:'Full crisis screen',crisisno:'Crisis "No" screen',safety:'"Do you feel safer?"',
    calm:'Calm',connect:'Connect',plan:'My Plan',set:'Settings'};
  const md=['# Spanish interface: review sheet (DRAFT)','',
    '**Generated by `npm run spanish-review` from `index.html`. Do not edit by hand;** change the strings in `L10N` in `index.html` and re-run.','',
    `\`SPANISH_ENABLED\` is **${w.eval('SPANISH_ENABLED')}**. While it is false there is no language switch and nobody sees Spanish.`,'',
    'Every Spanish line below is a **draft** (not reviewed). Please give each one a human translator\'s review, and the crisis-screen lines (marked **Crisis**) a clinician\'s review too. A draft crisis line is never shown, even with Spanish on, and a test fails if Spanish is turned on while any crisis line is still a draft.','',
    'Notes for the translator: keep "988", "911", "211" and "ZigZag Mind" as they are. Lines starting with a space or comma are joined to a name or number on screen (for example "Llamar a" + a name). `&` is shown on screen as "&".','',
    `Strings: ${Object.keys(L.en).length} (crisis-screen: ${Object.keys(L.en).filter(crisis).length}).`,''];
  let area='';
  for(const k of Object.keys(L.en)){
    const a=AREA[k.split('.')[0]]||k.split('.')[0];
    if(a!==area){ area=a; md.push('',`## ${a}`,'','| Key | English (live) | Spanish (draft) | Crisis | Status |','|---|---|---|---|---|'); }
    const e=L.es[k]||{};
    md.push(`| \`${k}\` | ${cell(L.en[k])} | ${cell(e.text||'(missing)')} | ${crisis(k)?'**Crisis**':''} | ${e.draft?'DRAFT':'reviewed'} |`);
  }
  md.push('');
  return md.join('\n');
}
if(require.main===module){ fs.writeFileSync(path.join(__dirname,'docs','SPANISH_REVIEW.md'),build()); console.log('Wrote docs/SPANISH_REVIEW.md'); }
module.exports={build};
